import os
import subprocess
import logging
from pathlib import Path
from jinja2 import Template

logger = logging.getLogger("vhostfactory")


class NginxManager:
    def __init__(self, config):
        self.config = config
        self.sites_available = config.get("nginx_sites_available")
        self.sites_enabled = config.get("nginx_sites_enabled")

    def generate_config(self, domain, stack_type, root_path=None):
        template_dir = Path(self.config.get("templates_dir", "/opt/vhostfactory/templates"))

        template_map = {
            "php": "nginx_php.conf.j2",
            "node": "nginx_node.conf.j2",
            "static": "nginx_static.conf.j2"
        }

        template_file = template_dir / template_map.get(stack_type, "nginx_static.conf.j2")

        if not template_file.exists():
            logger.error(f"Template not found: {template_file}")
            return None

        with open(template_file, 'r') as f:
            template_content = f.read()

        template = Template(template_content)

        context = {
            "domain": domain,
            "stack_type": stack_type,
            "root_path": root_path or f"/var/www/{domain}",
            "php_fpm_socket": self.config.get("php_fpm_socket"),
            "node_port": self.config.get("node_default_port", 3000)
        }

        return template.render(context)

    def write_config(self, domain, config_content):
        config_path = os.path.join(self.sites_available, domain)

        try:
            os.makedirs(self.sites_available, exist_ok=True)
            with open(config_path, 'w') as f:
                f.write(config_content)
            logger.info(f"Wrote Nginx config: {config_path}")
            return config_path
        except Exception as e:
            logger.error(f"Failed to write Nginx config: {e}")
            return None

    def enable_config(self, domain):
        sites_available_path = os.path.join(self.sites_available, domain)
        sites_enabled_path = os.path.join(self.sites_enabled, domain)

        try:
            os.makedirs(self.sites_enabled, exist_ok=True)

            if os.path.islink(sites_enabled_path):
                os.remove(sites_enabled_path)

            os.symlink(sites_available_path, sites_enabled_path)
            logger.info(f"Enabled Nginx config: {sites_enabled_path}")
            return True
        except Exception as e:
            logger.error(f"Failed to enable Nginx config: {e}")
            return False

    def reload_nginx(self):
        try:
            result = subprocess.run(
                ["nginx", "-s", "reload"],
                capture_output=True,
                text=True,
                timeout=10
            )
            if result.returncode == 0:
                logger.info("Nginx reloaded successfully")
                return True
            else:
                logger.error(f"Nginx reload failed: {result.stderr}")
                return False
        except Exception as e:
            logger.error(f"Failed to reload Nginx: {e}")
            return False

    def is_auto_generated(self, domain):
        config_path = os.path.join(self.sites_available, domain)

        if not os.path.exists(config_path):
            return False

        try:
            with open(config_path, 'r') as f:
                return "AUTO-GENERATED by vhostfactory" in f.read()
        except Exception as e:
            logger.error(f"Error checking auto-generated flag: {e}")
            return False

    def delete_config(self, domain):
        if not self.is_auto_generated(domain):
            logger.warning(f"Config for {domain} is not auto-generated, skipping deletion")
            return False

        try:
            sites_available_path = os.path.join(self.sites_available, domain)
            sites_enabled_path = os.path.join(self.sites_enabled, domain)

            if os.path.islink(sites_enabled_path):
                os.remove(sites_enabled_path)

            if os.path.exists(sites_available_path):
                os.remove(sites_available_path)

            logger.info(f"Deleted Nginx config for {domain}")
            return True
        except Exception as e:
            logger.error(f"Failed to delete Nginx config: {e}")
            return False
